- .github/CODEOWNERS
- LICENSE
- README.md
- package.json
- Add MIT license
- Clean up badges
- Restore CODEOWNERS
- Unscope package name
> Tweak for seek-oss

- .github/workflows/validate.yml
This intentionally leaves off Loki for now; we can come back to that when someone is feeling braver. The problem we observed internally was that Loki would not correctly wait for assets to load in.
> Add rudimentary validation workflow

- README.md
- Add an emoji approximation
- Add missing ToC entries
- Plug developer.seek.com
- Update badges
> chore(docs): Tweak README

- .github/workflows/release.yml
- README.md
- package.json
- yarn.lock
This steals @aaronvanston's work on Wingman.
> chore(storybook): Deploy to GitHub Pages

- package.json
- src/components/SmartTextLink.tsx
- src/private/ExternalTextLink.tsx
- src/private/InternalTextLink.test.ts
- src/private/InternalTextLink.tsx
- src/private/SpacedHeading.treat.ts
- src/private/SpacedHeading.tsx
- src/stories/index.stories.tsx
- Represent heading anchors with a Braid IconLink
- Add offset to anchor scroll point
- Preserve `v` version parameter
> feat(SmartTextLink): Rework anchors

- README.md
- src/private/InternalTextLink.tsx
- Fix missing URL global on sku static render
- Fix rogue default event interfering with our smooth scrolling
> fix(SmartTextLink): Squash bugs

- .loki/reference/chrome_laptop_MdxProvider_Blockquote.png
- .loki/reference/chrome_laptop_MdxProvider_Code.png
- .loki/reference/chrome_laptop_MdxProvider_Combination.png
- .loki/reference/chrome_laptop_MdxProvider_Headings.png
- .loki/reference/chrome_laptop_MdxProvider_ImagesInternal.png
- .loki/reference/chrome_laptop_MdxProvider_Inline.png
- .loki/reference/chrome_laptop_MdxProvider_Lists.png
- .loki/reference/chrome_laptop_MdxProvider_Table.png
- .loki/reference/chrome_laptop_SmartTextLink_Custom.png
- .loki/reference/chrome_laptop_TocRenderer_Example.png
- .loki/reference/chrome_laptop_WrapperRenderer_Example.png
- package.json
- src/stories/decorator.tsx
- yarn.lock
This is in preparation for some actual design updates.
I believe there is noise in the snapshots due to a recent Loki change to font rendering.
> chore: Switch Storybook to APAC theme

- src/components/InternalLink.tsx
This lets us use `InternalLink` in our navigation menus and sidebars.
> feat(InternalLink): Accept NavLink props

- src/hooks/useImageStyles.treat.ts
This appears to have been a long-standing issue.
> fix(images): Remove unintentional bottom margin

- .loki/reference/chrome_laptop_InlineCode_Custom.png
- .loki/reference/chrome_laptop_MdxProvider_Lists.png
- README.md
- src/components/InlineCode.treat.ts
- src/components/InlineCode.tsx
- src/index.ts
- src/private/useMdxComponents.treat.ts
- src/private/useMdxComponents.tsx
- src/stories/index.stories.tsx
- src/stories/markdowns/lists.mdx
This also corrects a line height issue that caused lines with inline code to look droopy next to the numbering of an ordered list.
---
Example of the issue on https://developer.seek.com/auth/browser-tokens#request-parameters:
> feat(InlineCode): Add component

- package.json
- yarn.lock
There's an XSS vulnerability in prismjs <1.21:
https://snyk.io/vuln/SNYK-JS-PRISMJS-597628
> fix(deps): refractor ^3.1.0

- src/components/InternalLink.tsx
- src/components/SmartTextLink.tsx
- src/private/ExternalTextLink.tsx
- src/private/InternalTextLink.tsx
- types.d.ts
This supports the optional title on Markdown links, e.g.
```markdown
My favorite search engine is [Duck Duck Go](https://duckduckgo.com "The best search engine for privacy").
```
> feat(MdxProvider): Add link title support

- src/components/CodeBlock/GraphQLPlaygroundAction.tsx
> fix(CodeBlock): Fix URL ReferenceError

- package.json
This is what #134 should've been.
> fix(deps): Allow React 17 peer

- src/components/Table.tsx
- src/private/Table.treat.ts
- src/private/Table.tsx
- src/stories/index.stories.tsx
| `width={undefined}` (default) | `width="full"`
| :-: | :-:
| ![Screen Shot 2021-04-12 at 4 17 48 pm](https://user-images.githubusercontent.com/25572311/114349045-b8aca580-9baa-11eb-90bd-41a8ee5ed1ba.png) | ![Screen Shot 2021-04-12 at 4 17 54 pm](https://user-images.githubusercontent.com/25572311/114349051-ba766900-9baa-11eb-84e5-00bf1aceabc9.png)
> feat(Table): Support full width option

- remark/imageToJsx.test.ts
Jest was clobbering the old snapshots. I left this out of #56 as that was a large enough PR as-is.
> Fix snapshot indentation

- package.json
- webpack/webpackPlugin.js
- yarn.lock
- Handle omitted `config.mermaid` properly
- Try to hack around `svgo-loader` resolution issues
> fix(webpack): Patch up config

- package.json
- yarn.lock
V3 doesn't have a tonne of documentation and I'm not brave enough to tackle the upgrade right now.
> fix(deps): Downgrade svgo-loader

- package.json
This allows me to fix up the bad #249 release.
BREAKING CHANGE: Migrate to vanilla-extract
> fix: Include styles directory in bundle

- remark/mermaid/style.css
This regressed with a recent-ish version of Mermaid, as seen on our Developer Site:
https://developer.seek.com/static/dc6df606db5a6bf48dd1adf62657053e.svg
> fix(mermaid): Fix flowchart text styling

- remark/mermaid/style.css
> fix(mermaid): Style subgraphs

- src/private/useMdxComponents.tsx
These were spilling out of their containers.
> fix(MdxProvider): Handle mermaid diagram overflow

- src/components/TableRow.tsx
- src/private/TableCell.css.ts
- src/private/TableCell.tsx
- src/private/TableRow.css.ts
- src/private/TableRow.tsx
This provides some light visual emphasis to the row, which could be useful for our deep links on https://developer.seek.com/schema.
---
---
> feat(TableRow): Support selected prop

- package.json
- sku.config.js
- src/components/Blockquote.stories.tsx
- src/components/CodeBlock.stories.tsx
- src/components/CopyableText.stories.tsx
- src/components/InlineCode.stories.tsx
- src/components/InternalLink.stories.tsx
- src/components/MdxProvider.stories.tsx
- src/components/SmartTextLink.stories.tsx
- src/components/Table.stories.tsx
- src/components/TocRenderer.stories.tsx
- src/components/WrapperRenderer.stories.tsx
- src/storybook/controls.tsx
- src/storybook/decorator.tsx
- yarn.lock
For the most part, at least. Knobs have been deprecated in favour of Controls.
https://storybook.js.org/docs/react/essentials/controls
> Migrate to Storybook Controls

- .loki/reference/chrome_laptop_MDX_MdxProvider_Images_Internal.png
- package.json
- sku.config.js
- src/components/Blockquote.stories.tsx
- src/components/CodeBlock.stories.tsx
- src/components/CopyableText.stories.tsx
- src/components/InlineCode.stories.tsx
- src/components/InternalLink.stories.tsx
- src/components/MdxProvider.stories.tsx
- src/components/SmartTextLink.stories.tsx
- src/components/Table.stories.tsx
- src/components/TocRenderer.stories.tsx
- src/components/WrapperRenderer.stories.tsx
- src/storybook/controls.tsx
- src/storybook/decorators.tsx
- yarn.lock
Like https://github.com/seek-oss/wingman/pull/528 but for Scoobie.
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-addon-knobs
> Drop Storybook knobs

- package.json
- remark/imageToJsx.js
- remark/imageToJsx.test.ts
- remark/mermaid/style.css
- webpack/webpackPlugin.js
- yarn.lock
- https://github.com/svg/svgo-loader/blob/b9d6d488a72fdc67085df3a32dc85895b020f1b3/README.md#usage
- https://github.com/svg/svgo/blob/v2.4.0/README.md#configuration
> fix: svgo-loader ^3.0.0

- src/components/InternalLink.tsx
- yarn.lock
This started as a straightforward removal of type assertions and ended in sadness.
> fix(InternalLink): Ensure React Router v6 compat

- typography.ts
Per https://web.dev/defer-non-critical-css/#optimize.
> feat(typography): Load web fonts asynchronously

- webpack/index.d.ts
This seems to work okay with our other repos, though not sure if it's the best way to go about it given this is the first declaration file i've ever written 😅 .
> fix: Add `scoobie/webpack` type declaration

- yarn.lock
https://github.com/seek-oss/scoobie/runs/4586387435?check_suite_focus=true
> Relock to fix Storybook

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
- package.json
- Fix CodeQL branch warning
- Lock down permissions
- Pin action versions
> Uplift workflows

- package.json
- remark/mermaid/style.css
- sku.config.ts
- styles/index.ts
seek-oss/braid-design-system#1104
> fix: Match Braid 31.14 palette

- yarn.lock
I believe this is causing our release action to fail:
https://github.com/seek-oss/scoobie/runs/7205259022?check_suite_focus=true#step:6:17
> deps: Deduplicate Storybook package versions

- src/components/SmartTextLink.tsx
- src/private/ExternalTextLink.tsx
https://seek-oss.github.io/braid-design-system/components/TextLink/releases#v31.21.0
> feat(SmartTextLink): Propagate `icon` prop

- remark/mermaid/mermaid.config.json
- remark/mermaid/style.css
- https://mermaid.js.org/syntax/gantt.html
- https://github.com/mermaid-js/mermaid/blob/v10.1.0/packages/mermaid/src/defaultConfig.ts#L580-L581
> feat(mermaid): Style Gantt charts

- remark/mermaid/style.css
| Before | After
| :-: | :-:
| <img width="421" alt="Screenshot 2023-04-18 at 9 17 47 pm" src="https://user-images.githubusercontent.com/25572311/232761211-30ea8dab-1112-49c4-9051-4e96573cac93.png"> | <img width="421" alt="Screenshot 2023-04-18 at 9 17 48 pm" src="https://user-images.githubusercontent.com/25572311/232761228-849cb576-4de0-49c1-851c-fb9dab753539.png">
https://developer.seek.com/use-cases/application-export/candidate-profiles#data-structure
> fix(mermaid): Fix ERD styling

- package.json
- yarn.lock
Reverts seek-oss/scoobie#681
This broke things, will look more deeply later
> Revert "deps: npm dev dependencies"

- package.json
- yarn.lock
Reverts seek-oss/scoobie#683
lol
> Revert "Revert "deps: npm dev dependencies""

- .github/workflows/validate.yml
It seems to work @72636c - any memory?
Resolves https://github.com/seek-oss/scoobie/issues/4
> Try to remember why we don't have loki in CI

- .changeset/dirty-maps-battle.md
- .storybook/preview.tsx
- package.json
- src/components/InternalLink.tsx
- yarn.lock
> Change peer dep
