seek-oss/scoobie

README.md

Index is overloaded as is, and this is less likely to conflict with a hypothetical index.ts or index.tsx.

chore(docs): Recommend scoobie.d.ts filename

---

src/components/CodeBlock.tsx
src/components/MdxProvider.tsx
src/components/WrapperRenderer.tsx
src/private/CodeBlockWithPlayground.tsx
src/private/Wrapper.tsx
src/private/size.ts
src/private/useMdxComponents.treat.ts
src/private/useMdxComponents.tsx
src/private/useMdxWrapper.tsx

This essentially adds a library-wide scaling factor via the `size` prop. The default remains at `standard`, while we introduce a new `large` size that is more suitable for fluffy things like <https://partner.seek.com>.

feat: Support large size

---

.loki/reference/chrome_laptop_Headings_heading.png
.loki/reference/chrome_laptop_ToC_toc.png
src/private/SpacedHeading.tsx
src/stories/markdowns.stories.tsx
src/stories/markdowns/headings.mdx

When we had a heading that wrapped across multiple lines, its anchor decided to migrate to its own line. This fixes the issue by treating the anchor as ordinary inner text rather than using Braid's `<Inline>`.
---
Here's an example of the issue:

fix(MdxProvider): Keep heading anchors inline

---

src/private/InternalTextLink.tsx

The existing code made an assumption the entire page was being scrolled when calculating the scroll destination. However, in DEMI the content is in a separate scrollable `<div>` while the `<body>` remains scrolled to the top. When our smooth scrolling code ran it ended up trying to scroll the body down which ended up being a no-op.
I think the intent of the original override was to prevent the header text from being cut in half. We can kind of hack this by instead scrolling our *parent* in to view, which happens to be a stack div.

fix(InternalTextLink): Fix for scrollable elements

---

.loki/reference/chrome_laptop_MdxProvider_Code.png
.loki/reference/chrome_laptop_MdxProvider_Combination.png
.loki/reference/chrome_laptop_MdxProvider_ImagesInternal.png
.loki/reference/chrome_laptop_MdxProvider_Table.png
package.json
src/components/CodeBlock.treat.ts
src/components/CodeBlock.tsx
src/private/useMdxComponents.treat.ts
src/private/useMdxComponents.tsx
src/styles.ts
yarn.lock

This bundles a number of styling tweaks that bring us in line with the APAC Braid theme, which is now Scoobie's primary target.
- Round the borders of inline code, code blocks and tables.
- Use lighter borders for tables.
- Use body colour as the basis for code and table row backgrounds. This allows us to gain the bluish tint on the APAC theme without hardcoding colours like we did previously.
- Right-align line numbers in code blocks.
- Reduce inline code background height to prevent lines from hitting each other.

feat(MdxProvider): Uplift styling for APAC

---

src/private/useMdxComponents.tsx
types.d.ts

We've been incubating a Remark Mermaid plugin internally that renders diagrams out as `<span>`s. On mobile it probably makes sense for these diagrams to retain their original dimensions with the option to scroll, rather than shrinking them down to microscopic sizes.
This also wraps a few remaining elements in Braid `<Box>`es.

fix(MdxProvider): Wrap spans in scroll container

---

src/components/InternalLink.tsx

Not sure how I missed this; the immediate use case is to highlight the active section in a table of contents based on the location hash.

fix(InternalLink): Accept `isActive` prop

---

src/stories/decorator.tsx

This allows you to interactively play with different Braid themes and Scoobie's provider-level options like `graphqlPlayground` and `size`.

Configure provider Storybook knobs

---

.loki/reference/chrome_laptop_MdxProvider_ImagesInternal.png

This was from the margin fix in #46.

chore: Update stale image snapshot

---

src/components/CodeBlock.tsx

These are not useful in a less visual format. For example, Firefox's reader view just dumps a list of numbers in a section before the code.

fix(CodeBlock): Hide line numbers from readers

---

src/private/List.treat.ts
src/private/List.tsx
src/private/useMdxComponents.treat.ts
src/private/useMdxComponents.tsx

I'm planning to revise these so there is some semblance of semantic correctness; the CSS Grid approach weaves a bunch of `<span>`s between the `<li>`s. This is just a small refactor to precede that.

chore: Split out list components

---

.loki/reference/chrome_laptop_MdxProvider_Lists.png
.loki/reference/chrome_laptop_MdxProvider_Table.png
src/components/CodeBlock.tsx
src/components/MdxProvider.tsx
src/components/WrapperRenderer.tsx
src/private/List.treat.ts
src/private/List.tsx
src/private/size.ts
src/private/useMdxComponents.tsx
src/stories/decorator.tsx

This steals Braid's Bullet implementation which solves our long-standing alignment woes. This requires us to differentiate between ordered and unordered list items. We now do this via React context, which happens to free us from CSS selector specificity migraines.

fix(List): Align and round bullets better

---

src/private/List.treat.ts
src/private/List.tsx

Finally, some normal `<ul><li>...</li></ul>`s.
This uses a flexbox in each unordered list item to achieve bullet alignment. Unfortunately a similar approach can't be employed for ordered list items because they have a dynamic width based on the numbering, so we still need a grid/table-based solution there for dynamic alignment across columns and rows.

fix(List): Emit sensible HTML from unordered lists

---

src/private/List.treat.ts
src/private/List.tsx

This uses `display: contents` to allow for nested children in a grid. This is better than invalid markup, but there are accessibility issues with the implementation in most browsers :(
https://hiddedevries.nl/en/blog/2018-04-21-more-accessible-markup-with-display-contents

fix(List): Emit sensible HTML from ordered lists

---

src/components/CodeBlock.treat.ts
src/components/CodeBlock.tsx

There are some changes to the node structure in the latest version of react-syntax-highlighter. We now need to split the line numbers on the `Code` component rather than the `Pre` wrapper.
This fixes white screens in [v3.9.3](https://github.com/seek-oss/scoobie/releases/tag/v3.9.3).

fix(CodeBlock): Handle react-syntax-highlighter@13

---

src/components/CodeBlock.tsx

The async Prism implementation grants a smaller bundle size upfront, but it also seems to defer rendering of our code block container styling. This manifests as ugly pop in which is not present when using the sync version.

fix(CodeBlock): Load synchronously

---

src/components/CodeBlock.tsx

I was trying to be clever and prevent the shorthand `label` and `language` props from being provided alongside a complex `children`, but TypeScript doesn't seem to correctly infer this and throws false positives in consumer repositories.

fix(CodeBlock): Loosen prop typings

---

.loki/reference/chrome_laptop_MdxProvider_Combination.png
src/private/Prism.ts
src/stories/markdowns/combination.mdx

These are the enterprisiest languages so it's probable that we would provide some code samples in future.
- Register C# for highlighting
- Format Java display label
This also snapshots a short CodeBlock in a List to flag an existing issue. I believe it requires an upstream fix or some other workaround I haven't thought of yet.

fix(CodeBlock): Improve C# and Java

---

src/private/Prism.test.ts
src/private/Prism.ts

I figure that more languages follow title casing.

fix(CodeBlock): Title case languages by default

---

src/components/CodeBlock.tsx
src/components/CodeBlock/CodeChild.test.ts
src/components/CodeBlock/CodeChild.tsx
src/stories/index.stories.tsx

This is useful if you're intentionally inserting leading or trailing negative space into your code. An example of this is rendering a snippet of indented code.

feat(CodeBlock): Allow trimming to be disabled

---

.gitignore
README.md
src/components/InternalLink.tsx
src/components/ScoobieLink.tsx
src/components/SmartTextLink.tsx
src/index.ts
src/private/url.test.ts
src/private/url.ts
src/stories/decorator.tsx

Braid has deprecated custom `LinkRenderer` components in favour of the `linkComponent` prop on `BraidProvider`. It's about time we get on board with this change, as it allows us to customise rendering across all link components, including `ButtonLink`s.
BREAKING CHANGE: `MdxProvider` and `SmartTextLink` no longer customise the rendering of internal links by themselves. Supply `ScoobieLink` to `BraidProvider` to restore this behaviour.
```diff
import { BraidProvider } from 'braid-design-system';
import apacTheme from 'braid-design-system/themes/apac';
+ import { ScoobieLink } from 'scoobie';
export const App = () => (
-   <BraidProvider theme={apacTheme}>
+   <BraidProvider linkComponent={ScoobieLink} theme={apacTheme}>
...
</BraidProvider>
);
```

feat(ScoobieLink): Add component

---

src/components/ScoobieLink.tsx

The reset messes with `:visited` styling as an internal Braid link renderer.

fix(ScoobieLink): Disable internal link reset

---

package.json
yarn.lock

This should force consumers to update to a patched version of `prismjs`.
https://app.snyk.io/vuln/SNYK-JS-PRISMJS-1076581

fix: refractor ^3.3.1

---

src/components/CodeBlock/LineNumbers.tsx
src/components/CodeBlock/Lines.tsx

Firefox 87+, Capsize 2 and `pre` whitespacing don't seem to get along with each other. This fixes the issue at the cost of an extra node per line, and I've checked that it hasn't regressed in Chrome or Safari.

fix(CodeBlock): Trim Firefox line spacing

---

package.json
yarn.lock

I noticed that our Developer Site syntax highlighting has regressed:
1. GraphQL variables are a pale blue with poor contrast
2. JSON comments (that we use in JSONC blocks) are highlighted as errors
These changes were made in v1.2.0, so we can restore our expected highlighting by locking v1.1.1 in. We probably need to upstream changes before we can land future versions; the first point requires a fix to
the prism-react-renderer GitHub theme and the second point requires us to contribute a new JSONC language definition to prism that is distinct from the base JSON language definition.

fix(CodeBlock): Lock prism-react-renderer version

---

.github/renovate.json5

We depend on matching sku's internal Storybook version, which is still stuck at v5 for now. If this doesn't work due to grouping shenanigans, I'll have to copy+paste the whole config.

Try to disable `@storybook/addons` majors

---

src/private/Table.tsx
yarn.lock

This is broken on classnames 2.3+, which can be pulled in via Renovate lock file maintenance.
https://github.com/JedWatson/classnames/issues/240

fix(Table): Avoid object-style classnaming

---

src/components/CopyableText.tsx

Last stop on the update-to-new-api train. Updating scoobie should flow down to everything else that's left (as per a search for `CopyableText`)

refactor(CopyableText): Use clipboard API

---

src/components/InlineCode.css.ts
src/components/InlineCode.tsx

This is some fairly jank code to get `InlineCode` to automatically detect when its contents are a hex colour code and display a preceding preview.

fix(InlineCode): Show hex colour previews

---

remark/mermaid/style.css

I noticed that the edge labels on our flowcharts are drooping and getting cut off:
https://developer.seek.com/static/311adde78c8acf676510c8b8ae84f47a.svg

fix(mermaid): Improve edge label alignment

---

README.md
src/components/ScoobieLink.tsx

This adds a third case to custom links behaviour. 
Previously we account for internal and external links based on `href` attribute. Here we use `download` attribute to determine if the link is for download and not to be navigated to (no client side rendering happens)

feat(ScoobieLink): Render download links as anchors

---

src/components/Blockquote.stories.tsx
src/components/CodeBlock.stories.tsx
src/components/CopyableText.stories.tsx
src/components/InlineCode.stories.tsx
src/components/InternalLink.stories.tsx
src/components/MdxProvider.stories.tsx
src/components/SmartTextLink.stories.tsx
src/components/Table.stories.tsx
src/components/TocRenderer.stories.tsx
src/components/WrapperRenderer.stories.tsx
src/storybook/decorators.tsx

This should remove the MdxProvider knobs from standalone component
stories, where they are ineffectual.

Split out MdxDecorator

---

package.json
remark/imageToJsx.js
remark/imageToJsx.test.ts
webpack/webpackPlugin.js

It seems we were lucking out by resolving a 4.x version of `file-loader` previously. Newer versions default to ESM and allow us to unify our code paths.
https://github.com/webpack-contrib/file-loader/blob/master/CHANGELOG.md#500-2019-11-22

fix(deps): Pin file-loader 6

---

package.json
src/components/InternalLink.tsx
src/components/ScoobieLink.tsx
yarn.lock

BREAKING CHANGE: Upgrade to `react-router-dom@5.3.0` or newer.
BREAKING CHANGE: Switch from `activeClassName` to a `className` function:
```diff
<InternalLink
- activeClassName="active"
- className="default"
+ className={(isActive) => ({ active: isActive, default: true })}
href="/"
/>

feat(InternalLink): Support React Router 6

---

src/components/InternalLink.tsx

With React Router v5 types, this was complaining that the `isActive` prop does not exist in the `never` else case.

fix(InternalLink): Fix React Router v5 typing

---

README.md
typography.ts

The previous `onload` handlers weren't compatible.

fix(typography): Support CSP script hashes

---

src/components/MdxProvider.tsx
yarn.lock

This was caused by conflicting `@types/react` versions.

fix: Revert a #423 type assertion

---

package.json
src/components/CodeBlock/GraphQLPlaygroundAction.tsx
src/components/CopyableText.stories.tsx
src/components/CopyableText.tsx
yarn.lock

BREAKING CHANGE: Braid 31.21+ is now required.
`CopyableText` now has separate `copiedIcon` and `copyIcon` properties that occupy Braid's built-in text icon slots. You can hide the default icon when customising the label via `false`:
```diff
<CopyableText
+ copyIcon={false}
copyLabel="Copy me"
/>
```

feat(CopyableText): Use text icon slots

---

src/storybook/controls.tsx
src/storybook/decorators.tsx

The dynamic loadable approach we had before doesn't work with Braid 32. This gives us an opportunity to simplify our code as we don't need to microoptimise our Storybook.

Load Braid themes explicitly in Storybook

---

src/components/InlineCode.tsx

This matches `Badge` and works better with the `seekJobs` theme.
https://github.com/seek-oss/braid-design-system/blob/e42c6f9168904f6b607c74157cafebf9b0147489/packages/braid-design-system/src/lib/components/Badge/Badge.tsx#L90

fix(InlineCode): Use standard border radius

---

src/components/CodeBlock/GraphQLPlaygroundAction.tsx
src/private/url.ts

In Storybook 7, we can't resolve `url`. I'm assuming SB6 was polyfilling this.
`URL` and `URLSearchParam` are both available as globals in node and should be available in browsers - https://nodejs.org/api/globals.html

fix: Remove unresolvable `url` module import

---

src/private/Prism.ts

JSON syntax highlighting is broken, likely since merging this PR in https://github.com/seek-oss/scoobie/pull/509 which upgraded `prism-react-renderer` from 1.3.5 to 2.0.4. This newer version does not have JSON as a bundled language -> https://github.com/FormidableLabs/prism-react-renderer/blob/master/packages/generate-prism-languages/index.ts#L9-L23, hence we need to pull it in ourselves

fix(CodeBlock): Fix JSON syntax highlighting

---

README.md
src/components/InternalLink.tsx
src/components/ScoobieLinkProvider.tsx
src/index.ts
src/private/url.test.ts
src/private/url.ts

This also removes the non-standard `v-panel` from default behaviour.
```diff
+ <ScoobieLinkProvider propagateSearchParams={['debug', 'v']}>
<BraidProvider linkComponent={ScoobieLink} theme={apacTheme}>
<TextLink href="/root-relative">Internal link</TextLink>
</BraidProvider>
+ </ScoobieLinkProvider>
```

feat: Support custom search param propagation

---

src/private/Prism.ts
src/storybook/markdown/code.mdx

We've been using `diff` code blocks but they lack syntax highlighting:
https://developer.seek.com/migration-guides/jobstreet-and-jobsdb-uplift/phase-2-job-posting/ad-selection#option-1-ad-selection-panel

fix(CodeBlock): Support `diff` highlighting

---

package.json
yarn.lock

BREAKING CHANGE: If importing `scoobie/webpack`, you'll need to add this optional peer dependency:
```sh
yarn add '@mdx-js/loader@^1.6.22'
```
This is to avoid including dependencies which have some security vulnerabilities (CVE-2020-7753, CVE-2022-37601, CVE-2022-37599, CVE-2022-37603) if unnecessary. This is a bridge until https://github.com/seek-oss/scoobie/issues/566

feat: Make @mdx-js/loader an optional peer dependency

---

.github/workflows/validate.yml

We don't have `@seek` deps on this OSS project.
https://github.com/seek-oss/scoobie/actions/runs/6952083290/job/18915097308#step:5:10

Suppress sku telemetry warnings in CI

---

.changeset/forty-melons-rhyme.md
src/components/CodeBlock.tsx
src/components/Table.stories.tsx
src/components/Table.tsx
src/private/ScrollableInline.css.ts
src/private/ScrollableInline.tsx
src/private/Table.tsx

| Default | `overflowX="scroll"` | `overflowX="scroll" whiteSpace="nowrap"`
| :-: | :-: | :-:
| ![Screen Shot 2024-01-23 at 08 28 04](https://github.com/seek-oss/scoobie/assets/25572311/cd299385-51a4-4835-95e8-c3ea99c6928a) | ![Screen Shot 2024-01-23 at 08 28 12](https://github.com/seek-oss/scoobie/assets/25572311/f5289874-855d-4493-98fa-43c449eef1d1) | ![Screen Shot 2024-01-23 at 08 28 16](https://github.com/seek-oss/scoobie/assets/25572311/02171a66-d1da-4f61-a413-02913620b3ac)
---
Motivation: https://developer.seek.com/schema can look a bit shoddy on mobile:

feat(Table): Add `overflowX` and `whiteSpace` props

---

.changeset/tidy-suits-beg.md
remark/mermaid/style.css

Prevent flowchart labels from being cut off

---

.changeset/old-tomatoes-hide.md
remark/mermaid/style.css

The previous approach wasn't:
- Particularly nice to look at
- Correctly spanning the width of the label
- Going to work well with dark mode
| Mode | Before | After
| :-: | :-: | :-:
| Light | ![Screen Shot 2024-09-04 at 10 26 47](https://github.com/user-attachments/assets/f7431568-6d60-439a-9260-b242f4e3e00a) | ![Screen Shot 2024-09-04 at 10 26 54](https://github.com/user-attachments/assets/b440c467-4a75-4e5b-ab51-0404a5f7b87b)
| Dark | ![Screen Shot 2024-09-04 at 10 27 05](https://github.com/user-attachments/assets/db7cc3fd-6285-4f78-908d-f814eb51791e) | ![Screen Shot 2024-09-04 at 10 27 09](https://github.com/user-attachments/assets/1548176e-9bf8-47ab-a700-e2a01899749c)

mermaid: Outline edge labels

---

.changeset/late-plums-flow.md
remark/mermaid/style.css

These were just showing as scrollbars 🙂‍↔️

mermaid: Fix Chrome regression with label overflow hack

---

.changeset/poor-doors-explain.md
remark/mermaid/style.css

I decided to actually RTFM. I think Blink is doing the specful thing here and this should be the proper fix for #698 / #707.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow#description
> Setting `overflow` to visible in one direction (i.e. `overflow-x` or
> `overflow-y`) when it isn't set to `visible` or `clip` in the other
> direction results in the `visible` value behaving as `auto`.

mermaid: Fix flowchart labels being cut off in Chrome

---

.changeset/rotten-yaks-shout.md
remark/mermaid/style.css

The primary objective here is to semanticise our CSS variables so they still make sense when we're switching between light & dark modes.
---
The text (shadow) improvements should make extensions like Dark Reader a bit more viable in the interim:
| Before | After
| :-: | :-:
| ![Screenshot 2024-09-11 at 6 06 52 PM](https://github.com/user-attachments/assets/b1d93c75-b9b5-40a6-afd2-7089227cf3bd) | ![Screenshot 2024-09-11 at 6 06 51 PM](https://github.com/user-attachments/assets/3d852058-b55d-455c-88b4-b5669ab402f4)
| ![Screenshot 2024-09-11 at 6 13 12 PM](https://github.com/user-attachments/assets/250b7596-bdf0-45c1-9eac-c0a0dc772e47) | ![Screenshot 2024-09-11 at 6 13 14 PM](https://github.com/user-attachments/assets/26b603d4-e835-4935-9ca8-9d5e351eb8d9)

mermaid: Revise CSS styling

---

.changeset/fluffy-dryers-chew.md
remark/mermaid/style.css

I haven't bothered to dig into why these elements are added sometimes and omitted other times.

mermaid: Handle optional `tspan`s in sequence diagrams

---

.changeset/seven-kangaroos-repeat.md
src/components/CodeBlock.stories.tsx
src/components/CodeBlock.tsx

I've got a few use-cases where I have mixed content within within tabs, and it looks weird when the 'code block' tags jump down visually due to the top row

Support a minimal CodeBlock

---

.changeset/popular-hornets-cheat.md
src/components/CopyableText.tsx

This component is gnarly but BrandSelect currently uses it.
seek-oss/wingman#1266

CopyableText: Stop `onClick` propagation
